### ISSUE TITLE
[Suggestion] Publish the library to a Maven repository

### ISSUE THREAD

**Issue by Cubxity** [NFT-Worlds/WRLD-Payments-API#2]
As mentioned in the documentation, GitHub's package registry requires authentication for public packages. This may prove to be inconvenient for many.

## Suggestions
- Publish to [Maven Central](https://central.sonatype.org/publish/publish-guide/)
- Utilize [jitpack](https://jitpack.io/)
- Host a Maven repository, using something like [Reposilite](https://reposilite.com/)

**Comment by Jaxkr** [comment]
Thanks for your suggestion, we've spun up a Reposilite instance and updated the docs.
