### ISSUE TITLE
Finish anti-abuse implementation to guard config that may have sensitive keys.

### ISSUE THREAD

**Issue by iamarkdev** [NFT-Worlds/WRLD-Payments-API#7]
Finalize and implement a solution for preventing abuse from other installed plugins that may be trying to access the private key of the payments api set in the config. Ideally this implementation doesn’t limit developer functionality, but catches any external plugins trying to pull config data from the private key.

**Comment by Jaxkr** [comment]
This is complete now that we support the external Hotwallet API which completely removes private keys from the game server.
