### ISSUE TITLE
Create standard contract (ERC20, ERC721, etc) interaction convenience classes

### ISSUE THREAD

**Issue by iamarkdev** [NFT-Worlds/WRLD-Payments-API#8]
Expose a class generator convenience method for creating erc20, erc721 contract instances. The convenience class instance should abstract up common calls for these types of contracts like balanceOf, ownerOf, etc. For less likely used contract function calls, we should expose the ability to get the underlying instance of the contract wrapper class we attach to the convenience class instance at time of convenience class instantiation. Something like getContractWrapper()  / getContract(), etc.

**Comment by Jaxkr** [comment]
Additionally, support ERC1155.

**Comment by Jaxkr** [comment]
Initial versions of these have been released:

NFTs (ERC721): https://dev.nftworlds.com/nfts/player-ownership
ERC20: https://dev.nftworlds.com/payments/wrld-payments-api#getting-balances-for-custom-erc20-tokens

I've moved ERC-1155 to #12
