### ISSUE TITLE
Support $WRLD Payments From Bedrock Players

### ISSUE THREAD

**Issue by iamarkdev** [NFT-Worlds/WRLD-Payments-API#9]
Players on bedrock are unable to click links like on PC in order to quickly go to the pay page, for game clients that cannot click the pay link in chat, we need an alternative.

We propose giving a map item to the user interacting to purchase. The map item has a QR code generated on it. players can use their mobile wallet to scan the map's qr code on screen to direct them to the payment page on another device using mobile metamask, or another mobile wallet. Once a transaction is completed, remove the map qr item from the player's inventory.

This enables console based players to transact $WRLD in game.

**Comment by Jaxkr** [comment]
Now fully supported
